[package]
name = "cairo-lint"
description = "Core library for linting Cairo language code."
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
anyhow.workspace = true
cairo-lang-compiler.workspace = true
cairo-lang-defs.workspace = true
cairo-lang-diagnostics.workspace = true
cairo-lang-filesystem.workspace = true
cairo-lang-semantic.workspace = true
cairo-lang-syntax.workspace = true
cairo-lang-test-plugin.workspace = true
cairo-lang-utils.workspace = true
if_chain.workspace = true
indoc.workspace = true
itertools.workspace = true
log.workspace = true
num-bigint.workspace = true
scarb-metadata.workspace = true
tempfile.workspace = true
which.workspace = true

[dev-dependencies]
ctor.workspace = true
insta.workspace = true
pretty_assertions.workspace = true
test-case.workspace = true

[workspace]
resolver = "2"
members = [
  "xtask"
]

[workspace.package]
version = "2.10.0"
edition = "2021"
repository = "https://github.com/software-mansion/cairo-lint"
license-file = "LICENSE"

# Managing dependencies on crates from starkware-libs/cairo repository:
#
# The Cairo compiler is made of a bunch of crates that inter-depend on each other and have
# synchronised versioning.
# It is very important to use a single revision of these crates in the entire Cairo toolchain,
# which consists of Cairo compiler, Scarb, CairoLS and other tools.
# The toolchain is eventually built by Scarb, which depends on everything other as regular crates.
# To ensure that all crates in the toolchain use the same revision of Cairo crates, we use a patch
# mechanism that Cargo provides.
# Because Cargo requires patches to change the crate source, we have an unspoken contract that
# all tools *always* depend on some crates.io versions of Cairo crates and Scarb uses
# [patch.crates.io] table to set final git revision for everything.
#
# To keep our Cargo.toml following this contract, always use `cargo xtask upgrade`
# for manipulating these dependencies.
[workspace.dependencies]
anyhow = "1.0.95"
cairo-lang-compiler = "*"
cairo-lang-defs = "*"
cairo-lang-diagnostics = "*"
cairo-lang-filesystem = "*"
cairo-lang-semantic = "*"
cairo-lang-syntax = "*"
cairo-lang-test-plugin = "*"
cairo-lang-utils = "*"
clap = { version = "4.5.31", features = ["derive"]}
ctor = "0.2.9"
if_chain = "1.0.2"
indoc = "2"
insta = "1.41.0"
itertools = "0.13.0"
log = "0.4.25"
num-bigint = "0.4.6"
pretty_assertions = "1.4.1"
scarb-metadata = "1.14.0"
serde = { version = "1", features = ["serde_derive"] }
serde_json = { version = "1" }
tempfile = "3"
test-case = "3.0"
which = "7"

# Here we specify real dependency specifications for Cairo crates *if* currently we want to use
# a particular unreleased commit (which is frequent mid-development).
# We list all Cairo crates that go into Scarb's compilation unit even if Scarb itself does not depend
# on some of them directly.
# This ensures no duplicate instances of Cairo crates are pulled in by mistake.
[patch.crates-io]
# original: cairo-lang-casm = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-casm = { path = "../cairo/crates/cairo-lang-casm" }
# original: cairo-lang-compiler = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-compiler = { path = "../cairo/crates/cairo-lang-compiler" }
# original: cairo-lang-debug = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-debug = { path = "../cairo/crates/cairo-lang-debug" }
# original: cairo-lang-defs = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-defs = { path = "../cairo/crates/cairo-lang-defs" }
# original: cairo-lang-diagnostics = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-diagnostics = { path = "../cairo/crates/cairo-lang-diagnostics" }
# original: cairo-lang-eq-solver = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-eq-solver = { path = "../cairo/crates/cairo-lang-eq-solver" }
# original: cairo-lang-filesystem = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-filesystem = { path = "../cairo/crates/cairo-lang-filesystem" }
# original: cairo-lang-formatter = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-formatter = { path = "../cairo/crates/cairo-lang-formatter" }
# original: cairo-lang-lowering = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-lowering = { path = "../cairo/crates/cairo-lang-lowering" }
# original: cairo-lang-parser = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-parser = { path = "../cairo/crates/cairo-lang-parser" }
# original: cairo-lang-plugins = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-plugins = { path = "../cairo/crates/cairo-lang-plugins" }
# original: cairo-lang-proc-macros = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-proc-macros = { path = "../cairo/crates/cairo-lang-proc-macros" }
# original: cairo-lang-project = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-project = { path = "../cairo/crates/cairo-lang-project" }
# original: cairo-lang-semantic = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-semantic = { path = "../cairo/crates/cairo-lang-semantic" }
# original: cairo-lang-sierra = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-sierra = { path = "../cairo/crates/cairo-lang-sierra" }
# original: cairo-lang-sierra-ap-change = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-sierra-ap-change = { path = "../cairo/crates/cairo-lang-sierra-ap-change" }
# original: cairo-lang-sierra-gas = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-sierra-gas = { path = "../cairo/crates/cairo-lang-sierra-gas" }
# original: cairo-lang-sierra-generator = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-sierra-generator = { path = "../cairo/crates/cairo-lang-sierra-generator" }
# original: cairo-lang-sierra-to-casm = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-sierra-to-casm = { path = "../cairo/crates/cairo-lang-sierra-to-casm" }
# original: cairo-lang-sierra-type-size = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-sierra-type-size = { path = "../cairo/crates/cairo-lang-sierra-type-size" }
# original: cairo-lang-starknet = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-starknet = { path = "../cairo/crates/cairo-lang-starknet" }
# original: cairo-lang-starknet-classes = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-starknet-classes = { path = "../cairo/crates/cairo-lang-starknet-classes" }
# original: cairo-lang-syntax = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-syntax = { path = "../cairo/crates/cairo-lang-syntax" }
# original: cairo-lang-syntax-codegen = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-syntax-codegen = { path = "../cairo/crates/cairo-lang-syntax-codegen" }
# original: cairo-lang-test-plugin = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-test-plugin = { path = "../cairo/crates/cairo-lang-test-plugin" }
# original: cairo-lang-test-utils = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-test-utils = { path = "../cairo/crates/cairo-lang-test-utils" }
# original: cairo-lang-utils = { git = "https://github.com/DelevoXDG/cairo", branch = "zdobnikau/diagnostics-all" }
cairo-lang-utils = { path = "../cairo/crates/cairo-lang-utils" }


[profile.ci]
inherits = "test"
strip = "debuginfo"
[profile.ci.package."rust-analyzer-salsa"]
opt-level = 3
