[workspace]
resolver = "2"
members = [
  "crates/cairo-lint-cli",
  "crates/cairo-lint-core",
  "crates/cairo-lint-test-utils",
  "xtask"
]

[workspace.package]
version = "2.10.0-rc.1"
edition = "2021"
repository = "https://github.com/software-mansion/cairo-lint"
license-file = "LICENSE"

[workspace.dependencies]
cairo-lang-compiler = "2.10.0-rc.1"
cairo-lang-utils = "2.10.0-rc.1"
cairo-lang-semantic = "2.10.0-rc.1"
cairo-lang-filesystem = "2.10.0-rc.1"
cairo-lang-diagnostics = "2.10.0-rc.1"
cairo-lang-test-plugin = "2.10.0-rc.1"
cairo-lang-syntax = "2.10.0-rc.1"
cairo-lang-defs = "2.10.0-rc.1"
cairo-lang-starknet = "2.10.0-rc.1"
cairo-lang-test-utils = "2.10.0-rc.1"
test-case = "3.0"
pretty_assertions = "1.4.1"
ctor = "0.2.9"
paste = "1.0.15"
itertools = "0.13.0"
log = "0.4.22"
clap = { version = "4.5.23", features = ["derive"]}
anyhow = "1.0.95"
smol_str = "0.2.2"
annotate-snippets = "0.11.5"
num-bigint = "0.4.6"
if_chain = "1.0.2"
